language: node_js
sudo: required

services:
    - docker

script:
  - docker build -t roude/simple-server .

deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push
